---
- name: Add Grafana repository file [RHEL/CentOS]
  template:
    src: "{{ grafana_yum_repo_template }}"
    dest: "/etc/yum.repos.d/{{ grafana_yum_repo_template | basename | regex_replace('\\.j2$', '') }}"
    force: true
    backup: true

- name: Install packages
  package:
    name: "grafana"
    state: present
  register: install_packages

- name: Enable and (re)start service
  service:
    name: grafana-server
    enabled: yes
    state: restarted
    use: systemd
  when: install_packages.changed

- name: Wait for grafana to start
  wait_for:
    port: "{{ grafana_port }}"