---
- hosts: all
  become: true
  become_user: root
  become_method: sudo
  roles:
    - role: grafana
    - role: nginx
    - role: firewalld
  tasks:
    - name: Enforce SELinux
      command: setsebool httpd_can_network_connect on -P
